name: ossia-python

on: push

jobs:
  build-macos:
    runs-on: macos-latest
    environment: 'Apple Certificate'
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: brew install ninja
    - name: Build
      run: | 
        cmake -B build -S ${GITHUB_WORKSPACE} -G Ninja \
          -DOSSIA_PYTHON_ONLY=1 \
          -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        cmake --build build
    - name: Code Signing
      shell: bash
      env:
        MAC_CERT_B64: ${{ secrets.MAC_CERT_B64 }}
        MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
        MAC_ALTOOL_PASSWORD: ${{ secrets.MAC_ALTOOL_PASSWORD }}
      run: |
        # Setup codesigning
        # Thanks https://www.update.rocks/blog/osx-signing-with-travis/
        (
          set +x
          KEY_CHAIN=build.keychain
          echo "$MAC_CERT_B64" | base64 --decode > ossia-cert.p12

          security create-keychain -p azure $KEY_CHAIN
          security default-keychain -s $KEY_CHAIN
          security unlock-keychain -p azure $KEY_CHAIN
          security import ossia-cert.p12 -k $KEY_CHAIN -P "$MAC_CERT_PASSWORD" -T /usr/bin/codesign;
          security set-key-partition-list -S apple-tool:,apple: -s -k azure $KEY_CHAIN

          rm -rf *.p12
        )

        security unlock-keychain -p azure build.keychain

        for lib in `find build -name "ossia_python.cpython*.so" -print`
        do
          echo Signing ${lib}
          codesign --force --timestamp --sign "ossia.io" ${lib}
        done
    - name: Build Wheel
      shell: bash
      run: |
        cmake --build build --target install
        python3 -m twine upload -u ${PYPIUSER} -p ${PYPIWORD} build/src/ossia-python/dist/pyossia*.whl || true

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: | 
        sudo apt-get update -yqq 
        sudo apt-get upgrade -yqq
        sudo apt-get install -yqq build-essential g++ ninja-build libavahi-client-dev
    - name: Build ossia-python
      run: | 
        cmake -B build -S ${GITHUB_WORKSPACE} -G Ninja -DOSSIA_PYTHON_ONLY=1
        cmake --build build
        cmake --build build --target install
#    - name: Build Wheel
#      run: ./ci/build-wheels.sh
#    - name: Archive Package
#      uses: actions/upload-artifact@v2
#      with:
#        name: ossia-pd
#        path: install/ossia-pd-package/ossia